# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths:
      - LastJudge/**
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [ win-x64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Delete existing artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: '*'
        continue-on-error: true

      - name: Restore dependencies
        working-directory: LastJudge/LastJudge
        run: dotnet restore

      - name: Publish as single-file self-contained executable
        working-directory: LastJudge/LastJudge
        run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true /p:PublishTrimmed=false -o publish/${{ matrix.runtime }}

      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: LastJudge-${{ matrix.runtime }}
          path: LastJudge/LastJudge/publish/${{ matrix.runtime }}/*
      
      - name: Create ZIP file
        run: |
          cd LastJudge/LastJudge/publish/${{ matrix.runtime }}
          zip -r ../../../../release-${{ matrix.runtime }}.zip .

      - name: Delete previous "Latest" release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create/Update Rolling Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: LastJudge
          body: |
            LastJudge latest release.
            Commit: ${{ github.sha }}
            Runtime: `${{ matrix.runtime }}`
          files: release-${{ matrix.runtime }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
